name: Build

on:
  push:
    branches:
      - '**'  # all branches

permissions:
  contents: read

jobs:
  build:
    name: dotnet build + test
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK (x64)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
          architecture: x64

      - name: Setup .NET SDK (x86)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
          architecture: x86

      - name: dotnet build
        run: dotnet build -c Release

      - name: dotnet test
        run: dotnet test -c Release --no-build
